name: simple yml file for hellow-world
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout the code
      uses: actions/checkout@v2

    - name: print the hello world
      run: echo "Hello-World"
